pipeline {
    agent any

    environment {
        ANSIBLE_HOST = 'ubuntu@10.0.3.20'
        PROJECT_DIR = '~/disaster_recovery_project'
        ANSIBLE_DIR = '~/disaster_recovery_project/ansible'
    }

    stages {
        stage('Deploy via Ansible') {
            steps {
                withCredentials([file(credentialsId: 'rg12.pem', variable: 'PEM_FILE')]) {
                    sh """
                        dir
                        chmod 400 ${PEM_FILE}
                        
                        EOF
                    """
                }
            }
        }
    }
}
