pipeline {
    agent any

    environment {
        ANSIBLE_HOST = 'ubuntu@10.0.3.20'
        PROJECT_DIR = '~/disaster_recovery_project'
        ANSIBLE_DIR = '~/disaster_recovery_project/ansible'
    }

    stages {
        stage('Deploy via Ansible') {
            steps {
                sshagent(credentials: ['rg12.pem']) {
                    sh """
                        ssh -o StrictHostKeyChecking=no ${env.ANSIBLE_HOST} << 'ENDSSH'
                        set -e
                        cd ${env.PROJECT_DIR}

                        git fetch --all
                        git reset --hard origin/\$(git rev-parse --abbrev-ref HEAD)
                        git pull -X theirs origin \$(git rev-parse --abbrev-ref HEAD)

                        cd ${env.ANSIBLE_DIR}
                        ansible-playbook -i inventory.ini deploy.yaml
                        ENDSSH
                    """
                }
            }
        }
    }
}
