- name: Deploy Docker Compose on AWS Servers
  hosts: awsservers
  become: true
  tasks:
    - name: Ensure Docker is installed
      apt:
        command: sudo docker --version

    - name: Ensure Docker Compose is installed
      apt:
        command: sudo docker-compose --version

    - name: Create application directory
      file:
        path: /home/{{ ansible_user }}/app
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Copy application files to AWS servers
      copy:
        src: ../app/
        dest: /home/{{ ansible_user }}/app/
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Stop and remove all running containers
      shell: |
        docker ps -q | xargs -r docker stop
        docker ps -aq | xargs -r docker rm
      ignore_errors: yes

    - name: Run Docker Compose on AWS servers
      command: docker-compose --env-file aws.env up --build -d
      args:
        chdir: /home/{{ ansible_user }}/app

- name: Deploy Docker Compose on Azure Servers
  hosts: azureservers
  become: true
  tasks:
    - name: Ensure Docker is installed
      apt:
        command: sudo docker --version

    - name: Ensure Docker Compose is installed
      apt:
        command: sudo docker --version

    - name: Create application directory
      file:
        path: /home/{{ ansible_user }}/app
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Copy application files to Azure servers
      copy:
        src: ../app/
        dest: /home/{{ ansible_user }}/app/
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Stop and remove all running containers
      shell: |
        docker ps -q | xargs -r docker stop
        docker ps -aq | xargs -r docker rm
      ignore_errors: yes
    
    - name: Run Docker Compose on Azure servers
      command: docker-compose --env-file azure.env up --build -d
      args:
        chdir: /home/{{ ansible_user }}/app
