---
- name: Install Docker Compose
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    docker_compose_version: "2.24.6"
    docker_compose_path: "/usr/local/bin/docker-compose"

  tasks:
    - name: Ensure curl is installed
      apt:
        name: curl
        state: present
        update_cache: yes

    - name: Set docker compose download URL
      set_fact:
        docker_compose_url: "https://github.com/docker/compose/releases/download/v{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"

    - name: Download Docker Compose binary
      get_url:
        url: "{{ docker_compose_url }}"
        dest: "{{ docker_compose_path }}"
        mode: "0755"

    - name: Verify docker-compose installation
      command: docker-compose --version
      register: compose_version

    - name: Show Docker Compose version
      debug:
        msg: "Installed Docker Compose version: {{ compose_version.stdout }}"
